name: wwwbank
description: "wwwBank: Learn Flutter web accessibility by building a banking dashboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  google_fonts: ^6.1.0
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
